import type { GameState } from '../types/game';
import { advanceMonthCounter } from './gameEngine';
import { settleEconomy } from '../systems/economySystem';
import { settleHealth } from '../systems/healthSystem';
import { advanceWorld } from '../systems/worldSystem';
import { triggerMonthlyEvent } from '../systems/eventSystem';
import { settleCareerOpportunities } from '../systems/careerSystem';
import { checkAchievements } from '../systems/achievementSystem';
import { checkEnding } from '../systems/endingSystem';
import { addPeriodicReviews, settleHiddenState } from '../systems/reviewSystem';
import { settleLaborMarket } from '../systems/laborMarketSystem';
import { settleFixedFinance } from '../systems/financeSystem';
import { settleHealthDebt } from '../systems/healthDebtSystem';
import { settleRelationshipDebt } from '../systems/relationshipSystem';
import { settleLifeStagePressure } from '../systems/lifePressureSystem';
import { recordTurningPoints } from '../systems/decisionLogSystem';
import { settleCrisisState } from '../systems/crisisSystem';

export function settleMonth(state: GameState): GameState {
  if (state.pendingEventChoice) return state;
  const before = state;
  let next = advanceMonthCounter(state);
  next = advanceWorld(next);
  next = settleLaborMarket(next);
  next = settleEconomy(next);
  next = settleFixedFinance(next);
  next = settleHealth(next);
  next = settleHealthDebt(next);
  next = settleHiddenState(next);
  next = settleRelationshipDebt(next);
  next = settleCareerOpportunities(next);
  next = triggerMonthlyEvent(next);
  next = settleLifeStagePressure(next);
  next = addPeriodicReviews(next);
  next = recordTurningPoints(before, next);
  next = settleCrisisState(next);
  next = checkAchievements(next);
  next = checkEnding(next);
  return next;
}
